[2025-06-17T12:42:43.277+0530] {processor.py:161} INFO - Started process (PID=443) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:42:43.278+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:42:43.278+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:42:43.278+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:42:43.281+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:42:43.287+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:42:43.282+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:42:43.288+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:42:43.304+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.030 seconds
[2025-06-17T12:43:34.728+0530] {processor.py:161} INFO - Started process (PID=507) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:43:34.737+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:43:34.738+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:43:34.738+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:43:34.744+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:43:34.746+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:43:34.744+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:43:34.746+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:43:34.764+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.038 seconds
[2025-06-17T12:44:22.894+0530] {processor.py:161} INFO - Started process (PID=572) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:44:22.897+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:44:22.898+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:44:22.897+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:44:22.903+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:44:22.904+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:44:22.903+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:44:22.904+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:44:22.918+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.028 seconds
[2025-06-17T12:46:07.290+0530] {processor.py:161} INFO - Started process (PID=671) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:46:07.304+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:46:07.305+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:46:07.304+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:46:07.309+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:46:07.311+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:46:07.310+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:46:07.311+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:46:07.335+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.047 seconds
[2025-06-17T12:46:58.680+0530] {processor.py:161} INFO - Started process (PID=1305) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:46:58.682+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:46:58.684+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:46:58.683+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:46:58.711+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:46:58.728+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:46:58.720+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:46:58.729+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:46:58.755+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.079 seconds
[2025-06-17T12:47:46.047+0530] {processor.py:161} INFO - Started process (PID=1509) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:47:46.049+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:47:46.050+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:47:46.050+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:47:46.053+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:47:46.055+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:47:46.054+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:47:46.055+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:47:46.069+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.024 seconds
[2025-06-17T12:48:32.462+0530] {processor.py:161} INFO - Started process (PID=1710) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:48:32.464+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:48:32.465+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:48:32.464+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:48:32.469+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:48:32.471+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:48:32.469+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:48:32.471+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:48:32.490+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.030 seconds
[2025-06-17T12:49:25.261+0530] {processor.py:161} INFO - Started process (PID=1979) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:49:25.263+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:49:25.264+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:49:25.263+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:49:25.266+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:49:25.268+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:49:25.267+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:49:25.268+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:49:25.283+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.024 seconds
[2025-06-17T12:50:12.382+0530] {processor.py:161} INFO - Started process (PID=2184) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:50:12.384+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:50:12.385+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:50:12.384+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:50:12.389+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:50:12.390+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:50:12.389+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:50:12.390+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:50:12.409+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.030 seconds
[2025-06-17T12:51:00.714+0530] {processor.py:161} INFO - Started process (PID=2412) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:51:00.715+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:51:00.716+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:51:00.716+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:51:00.721+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:51:00.723+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:51:00.722+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:51:00.723+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:51:00.740+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.031 seconds
[2025-06-17T12:51:50.989+0530] {processor.py:161} INFO - Started process (PID=2638) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:51:50.991+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:51:50.992+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:51:50.991+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:51:50.995+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:51:50.996+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:51:50.995+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:51:50.997+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:51:51.013+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.026 seconds
[2025-06-17T12:52:43.843+0530] {processor.py:161} INFO - Started process (PID=2887) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:52:43.845+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:52:43.846+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:52:43.845+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:52:43.851+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:52:43.853+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:52:43.852+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:52:43.853+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:52:43.872+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.032 seconds
[2025-06-17T12:53:37.732+0530] {processor.py:161} INFO - Started process (PID=3068) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:53:37.735+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:53:37.735+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:53:37.735+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:53:37.739+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:53:37.741+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:53:37.740+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:53:37.741+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:53:37.763+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.032 seconds
[2025-06-17T12:54:29.556+0530] {processor.py:161} INFO - Started process (PID=3173) to work on /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:54:29.557+0530] {processor.py:830} INFO - Processing file /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py for tasks to queue
[2025-06-17T12:54:29.558+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:54:29.558+0530] {dagbag.py:538} INFO - Filling up the DagBag from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:54:29.562+0530] {logging_mixin.py:188} WARNING - /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py:150 DeprecationWarning: UPath._from_parts is deprecated and should not be used. Please follow the universal_pathlib==0.2.0 migration guide at https://github.com/fsspec/universal_pathlib for more information.
[2025-06-17T12:54:29.564+0530] {logging_mixin.py:188} INFO - [2025-06-17T12:54:29.563+0530] {dagbag.py:348} ERROR - Failed to import: /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
Traceback (most recent call last):
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py", line 46, in <module>
    base = ObjectStoragePath("s3://aws_default@airflow-tutorial-data/")
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 150, in __new__
    return cls._from_parts(args_list, url=parsed_url, conn_id=conn_id, **kwargs)  # type: ignore
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 482, in _from_parts
    obj.__init__(*parts, **kwargs)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 251, in __init__
    self._storage_options = type(self)._parse_storage_options(
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/upath/core.py", line 406, in _parse_storage_options
    return inst._fs.storage_options
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/path.py", line 62, in _fs
    return self._store.fs
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 59, in fs
    return self._connect()
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/store/__init__.py", line 108, in _connect
    self._fs = get_fs(self.protocol, self.conn_id)
  File "/home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/io/__init__.py", line 93, in get_fs
    raise ValueError(f"No filesystem registered for scheme {scheme}") from None
ValueError: No filesystem registered for scheme s3
[2025-06-17T12:54:29.564+0530] {processor.py:842} WARNING - No viable dags retrieved from /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py
[2025-06-17T12:54:29.590+0530] {processor.py:183} INFO - Processing /home/priya/projects/snowflake_twitter_pipeline/venv/lib/python3.10/site-packages/airflow/example_dags/tutorial_objectstorage.py took 0.038 seconds
